### ISSUE TITLE
Syntax error (a typo) at line 547 of the relations.lgt file

### ISSUE THREAD

**Issue by pmoura** [Joelbyte/weak-bases#1]
There's a spurious character, "p" on that line after the right parenthesis.

**Comment by Joelbyte** [comment]
Thanks! I just fixed it.

-- Victor

Från: Paulo Moura
Skickat: ‎tisdag‎ den ‎10‎ ‎juni‎ ‎2014 ‎03‎:‎47
Till: Joelbyte/weak-bases

There's a spurious character, "p" on that line after the right parenthesis.
